### ISSUE TITLE
Add podspec to cocoapods repo

### ISSUE THREAD

**Issue by AYastrebov** [yatatsu/TKAlertController#1]
please, add a podspec to cocoapods repo

**Comment by yatatsu** [comment]
Thanks for your suggestion. 
For now, you can use in cocoapods like this.

```
pod 'TKAlertController', :git => 'https://github.com/yatatsu/TKAlertController.git'
```

**Comment by yatatsu** [comment]
Now, TKAlertController is added to Pods.
It is available thourgh CocoaPods without specifying repository. Thanks.

```
pod 'TKAlertController'
```
